version: '3.7'
services:
  app:
    container_name: app
    image: php_app.slim
    volumes:
      - ./src:/work
    working_dir: /work
    environment:
      - TZ=${TZ:-Asia/Tokyo}

  web:
    container_name: web
    image: nginx:1.17-alpine
    depends_on:
      - app
    ports:
      - ${WEB_PORT:-10080}:80
    volumes:
      - ./src:/work
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - TZ=${TZ:-Asia/Tokyo}
