name: test up
on: 
  push:
  schedule:
    - cron: "0 10 1 * *"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: make up
      - name: Put Test File
        run: mkdir src/public && echo '<?php phpinfo();' > src/public/index.php
      - name: Do Test
        run: sleep 1;curl -s --retry 10 --retry-connrefused http://127.0.0.1:10080/
